In [ ]:
# import json
# import os
# import pandas as pd
# import seaborn as sns
# import string
# from tqdm import tqdm
# import nltk
# nltk.download('punkt')
# from nltk.corpus import stopwords
# from nltk.stem import WordNetLemmatizer
# from nltk import word_tokenize
# import re
# from sklearn.model_selection import train_test_split, GridSearchCV
# from sklearn.preprocessing import LabelEncoder
# from sklearn.feature_extraction.text import TfidfVectorizer
# from sklearn.naive_bayes import MultinomialNB
# from sklearn.pipeline import Pipeline
# from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix, classification_report
# import numpy as np

# # Set random seed for reproducibility
# np.random.seed(42)

# tqdm.pandas()

# # Download necessary NLTK data
# nltk.download('punkt')
# nltk.download('stopwords')
# nltk.download('wordnet')

# # Load and preprocess the data
# df = pd.read_csv("OpenItemAll.csv")
# # df = df[~df['SubCategory'].isin(df['SubCategory'].value_counts()[df['SubCategory'].value_counts() < 2].index)]
# # df = df[~df['Category'].isin(df['Category'].value_counts()[df['Category'].value_counts() < 2].index)]
# df['SubCategory'] = df['SubCategory'].str.upper().str.strip().replace({'MEN DEODORANT': 'MEN DEODORANTS'})
# df['SubCategory'] = df['SubCategory'].str.upper().str.strip().replace({'SWEET CAKE': 'SWEET CAKES'})
# df['ProductName'] = df['ProductName'].fillna('')  # or df['ProductName'].astype(str)
# stop_words = set(stopwords.words('english'))

# def preprocess_text(text):
#     text = text.lower()
#     text = text.translate(str.maketrans('', '', string.punctuation))
#     tokens = word_tokenize(text)
#     tokens = [word for word in tokens if word not in stop_words]
#     lemmatizer = WordNetLemmatizer()
#     tokens = [lemmatizer.lemmatize(word) for word in tokens]
#     return ' '.join(tokens)

# df['ProductName'] = df['ProductName'].apply(preprocess_text)

# # Define features and target columns
# X = df['ProductName']
# target_columns = ['SubCategory', 'Category', 'Company', 'Brand']

# # Prepare dictionaries to store results for each target column
# models = {}
# encoders = {}
# grid_search_results = {}

# # Loop over each target column
# for target in target_columns:
#     print(f"\nTraining model for {target}...")

#     # Encode the target variable
#     encoder = LabelEncoder()
#     y = encoder.fit_transform(df[target])

#     # Store the encoder for later use
#     encoders[target] = encoder

#     # Split the data
#     x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.2,random_state=42)

#     # Define the pipeline
#     pipeline_nb = Pipeline([
#         ('vect', TfidfVectorizer(analyzer='char', stop_words='english')),
#         ('clf', MultinomialNB()),
#     ])

#     # Define the parameter grid
#     param_grid = {
#         'vect__ngram_range': [(1, 3), (2, 4), (3, 5)],
#         'vect__use_idf': [True, False],
#         'clf__alpha': [0.1, 0.01, 0.001]
#     }

#     # Perform grid search
#     grid_search_nb = GridSearchCV(pipeline_nb, param_grid, cv=5, n_jobs=-1, verbose=1)
#     grid_search_nb.fit(x_train, y_train)

#     # Store the trained model
#     models[target] = grid_search_nb
#     grid_search_results[target] = grid_search_nb.best_params_

#     # Make predictions
#     y_pred_nb = grid_search_nb.predict(x_test)

#     # Calculate and print metrics
#     accuracy_nb = accuracy_score(y_test, y_pred_nb)
#     precision_nb = precision_score(y_test, y_pred_nb, average='weighted', zero_division=1)
#     recall_nb = recall_score(y_test, y_pred_nb, average='weighted', zero_division=1)
#     f1_nb = f1_score(y_test, y_pred_nb, average='weighted', zero_division=1)
#     conf_matrix_nb = confusion_matrix(y_test, y_pred_nb)
#     unique_classes = np.unique(np.concatenate((y_test, y_pred_nb)))
#     target_names = encoder.inverse_transform(unique_classes)
#     # class_report_nb = classification_report(y_test, y_pred_nb, labels=unique_classes, target_names=target_names, zero_division=1)

#     print(f"Best parameters for {target}: ", grid_search_nb.best_params_)
#     print(f"Accuracy for {target}: {accuracy_nb}")
#     print(f"Precision for {target}: {precision_nb}")
#     print(f"Recall for {target}: {recall_nb}")
#     print(f"F1 Score for {target}: {f1_nb}")
#     print(f"Confusion Matrix for {target}:")
#     print(conf_matrix_nb)
#     # print("Classification Report:")
#     # print(class_report_nb)

# # # Predict for new data
# # docs_new = ['slice']
# # processed_docs_new = [preprocess_text(doc) for doc in docs_new]

# # for target in target_columns:
# #     predicted = models[target].predict(processed_docs_new)
# #     predicted_category = encoders[target].inverse_transform(predicted)
# #     print(f"Predicted {target} for '{docs_new[0]}': {predicted_category[0]}")

# # Define the new product names for which you want to predict the company, brand, and measurement type
# docs_new = ['pepsi500']  # You can add more product names as needed
# processed_docs_new = [preprocess_text(doc) for doc in docs_new]

# # Loop over the target columns to make predictions for each
# for target in target_columns:
#     predicted = models[target].predict(processed_docs_new)
#     predicted_category = encoders[target].inverse_transform(predicted)
#     print(f"Predicted {target} for '{docs_new[0]}': {predicted_category[0]}")



[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!



Training model for SubCategory...
Fitting 5 folds for each of 18 candidates, totalling 90 fits


/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_split.py:737: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=5.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/feature_extraction/text.py:547: UserWarning: The parameter 'stop_words' will not be used since 'analyzer' != 'word'
  warnings.warn(


Best parameters for SubCategory:  {'clf__alpha': 0.01, 'vect__ngram_range': (3, 5), 'vect__use_idf': False}
Accuracy for SubCategory: 0.8356532849169525
Precision for SubCategory: 0.8348256877124407
Recall for SubCategory: 0.8356532849169525
F1 Score for SubCategory: 0.8288257455616973
Confusion Matrix for SubCategory:
[[ 2  0  0 ...  0  0  0]
 [ 0  3  1 ...  0  0  0]
 [ 0  0  7 ...  0  0  0]
 ...
 [ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0 45]]

Training model for Category...
Fitting 5 folds for each of 18 candidates, totalling 90 fits


/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_split.py:737: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=5.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/feature_extraction/text.py:547: UserWarning: The parameter 'stop_words' will not be used since 'analyzer' != 'word'
  warnings.warn(


Best parameters for Category:  {'clf__alpha': 0.01, 'vect__ngram_range': (3, 5), 'vect__use_idf': True}
Accuracy for Category: 0.8597269854078408
Precision for Category: 0.8545040616810186
Recall for Category: 0.8597269854078408
F1 Score for Category: 0.8543691050203744
Confusion Matrix for Category:
[[151   1   0 ...   1   0   8]
 [  1  10   0 ...   0   0   0]
 [  0   0  25 ...   0   0   0]
 ...
 [  4   0   0 ... 149   0   0]
 [  2   0   0 ...   1   9   0]
 [  6   0   0 ...   0   0 227]]

Training model for Company...
Fitting 5 folds for each of 18 candidates, totalling 90 fits


/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_split.py:737: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=5.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/feature_extraction/text.py:547: UserWarning: The parameter 'stop_words' will not be used since 'analyzer' != 'word'
  warnings.warn(


Best parameters for Company:  {'clf__alpha': 0.1, 'vect__ngram_range': (3, 5), 'vect__use_idf': True}
Accuracy for Company: 0.8890457938269114
Precision for Company: 0.8903885242003067
Recall for Company: 0.8890457938269114
F1 Score for Company: 0.8658004306971294
Confusion Matrix for Company:
[[ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]
 [ 0  1  0 ...  0  0  0]
 ...
 [ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  1]
 [ 0  0  0 ...  0  0 27]]

Training model for Brand...
Fitting 5 folds for each of 18 candidates, totalling 90 fits


/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_split.py:737: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=5.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/feature_extraction/text.py:547: UserWarning: The parameter 'stop_words' will not be used since 'analyzer' != 'word'
  warnings.warn(


Best parameters for Brand:  {'clf__alpha': 0.01, 'vect__ngram_range': (3, 5), 'vect__use_idf': False}
Accuracy for Brand: 0.8818505816690202
Precision for Brand: 0.8997593660895931
Recall for Brand: 0.8818505816690202
F1 Score for Brand: 0.880136233834143
Confusion Matrix for Brand:
[[ 0  0  0 ...  0  0  0]
 [ 1  0  0 ...  0  0  0]
 [ 0  0  2 ...  0  0  0]
 ...
 [ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0 39]]
Predicted SubCategory for 'pepsi500': CARBONATED SOFT DRINKS
Predicted Category for 'pepsi500': BEVERAGES
Predicted Company for 'pepsi500': PEPSICO
Predicted Brand for 'pepsi500': PEPSI


In [1]:
import json
import os
import pandas as pd
import seaborn as sns
import string
from tqdm import tqdm
import nltk
nltk.download('punkt')
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
from nltk import word_tokenize
import re
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.preprocessing import LabelEncoder
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.pipeline import Pipeline
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix, classification_report
import numpy as np
import joblib

# Set random seed for reproducibility
np.random.seed(42)

tqdm.pandas()

# Download necessary NLTK data
nltk.download('punkt')
nltk.download('stopwords')
nltk.download('wordnet')

# Load and preprocess the data
df = pd.read_csv("OpenItemAll.csv")
# df = df[~df['SubCategory'].isin(df['SubCategory'].value_counts()[df['SubCategory'].value_counts() < 2].index)]
# df = df[~df['Category'].isin(df['Category'].value_counts()[df['Category'].value_counts() < 2].index)]
df['SubCategory'] = df['SubCategory'].str.upper().str.strip().replace({'MEN DEODORANT': 'MEN DEODORANTS'})
df['SubCategory'] = df['SubCategory'].str.upper().str.strip().replace({'SWEET CAKE': 'SWEET CAKES'})
df['ProductName'] = df['ProductName'].fillna('')  # or df['ProductName'].astype(str)
stop_words = set(stopwords.words('english'))

def preprocess_text(text):
    text = text.lower()
    text = text.translate(str.maketrans('', '', string.punctuation))
    tokens = word_tokenize(text)
    tokens = [word for word in tokens if word not in stop_words]
    lemmatizer = WordNetLemmatizer()
    tokens = [lemmatizer.lemmatize(word) for word in tokens]
    return ' '.join(tokens)

df['ProductName'] = df['ProductName'].apply(preprocess_text)

# Define features and target columns
X = df['ProductName']
target_columns = ['SubCategory', 'Category', 'Company', 'Brand']

# Prepare dictionaries to store results for each target column
models = {}
encoders = {}
grid_search_results = {}

# Directory to save the models and encoders
save_dir = 'models'
os.makedirs(save_dir, exist_ok=True)

# Loop over each target column
for target in target_columns:
    print(f"\nTraining model for {target}...")

    # Encode the target variable
    encoder = LabelEncoder()
    y = encoder.fit_transform(df[target])

    # Store the encoder for later use
    encoders[target] = encoder

    # Split the data
    x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

    # Define the pipeline
    pipeline_nb = Pipeline([
        ('vect', TfidfVectorizer(analyzer='char', stop_words='english')),
        ('clf', MultinomialNB()),
    ])

    # Define the parameter grid
    param_grid = {
        'vect__ngram_range': [(1, 3), (2, 4), (3, 5)],
        'vect__use_idf': [True, False],
        'clf__alpha': [0.1, 0.01, 0.001]
    }

    # Perform grid search
    grid_search_nb = GridSearchCV(pipeline_nb, param_grid, cv=5, n_jobs=-1, verbose=1)
    grid_search_nb.fit(x_train, y_train)

    # Store the trained model
    models[target] = grid_search_nb
    grid_search_results[target] = grid_search_nb.best_params_

    # Save the model and encoder
    joblib.dump(grid_search_nb, os.path.join(save_dir, f'{target}_model.pkl'))
    joblib.dump(encoder, os.path.join(save_dir, f'{target}_encoder.pkl'))

    # Make predictions
    y_pred_nb = grid_search_nb.predict(x_test)

    # Calculate and print metrics
    accuracy_nb = accuracy_score(y_test, y_pred_nb)
    precision_nb = precision_score(y_test, y_pred_nb, average='weighted', zero_division=1)
    recall_nb = recall_score(y_test, y_pred_nb, average='weighted', zero_division=1)
    f1_nb = f1_score(y_test, y_pred_nb, average='weighted', zero_division=1)
    conf_matrix_nb = confusion_matrix(y_test, y_pred_nb)
    unique_classes = np.unique(np.concatenate((y_test, y_pred_nb)))
    target_names = encoder.inverse_transform(unique_classes)
    # class_report_nb = classification_report(y_test, y_pred_nb, labels=unique_classes, target_names=target_names, zero_division=1)

    print(f"Best parameters for {target}: ", grid_search_nb.best_params_)
    print(f"Accuracy for {target}: {accuracy_nb}")
    print(f"Precision for {target}: {precision_nb}")
    print(f"Recall for {target}: {recall_nb}")
    print(f"F1 Score for {target}: {f1_nb}")
    print(f"Confusion Matrix for {target}:")
    print(conf_matrix_nb)
    # print("Classification Report:")
    # print(class_report_nb)

# Define the new product names for which you want to predict the company, brand, and measurement type
docs_new = ['pepsi500']  # You can add more product names as needed
processed_docs_new = [preprocess_text(doc) for doc in docs_new]

# Loop over the target columns to make predictions for each
for target in target_columns:
    model = joblib.load(os.path.join(save_dir, f'{target}_model.pkl'))
    encoder = joblib.load(os.path.join(save_dir, f'{target}_encoder.pkl'))

    predicted = model.predict(processed_docs_new)
    predicted_category = encoder.inverse_transform(predicted)
    print(f"Predicted {target} for '{docs_new[0]}': {predicted_category[0]}")


[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
[nltk_data] Downloading package wordnet to /root/nltk_data...



Training model for SubCategory...
Fitting 5 folds for each of 18 candidates, totalling 90 fits


/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_split.py:737: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=5.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/feature_extraction/text.py:547: UserWarning: The parameter 'stop_words' will not be used since 'analyzer' != 'word'
  warnings.warn(


Best parameters for SubCategory:  {'clf__alpha': 0.01, 'vect__ngram_range': (3, 5), 'vect__use_idf': False}
Accuracy for SubCategory: 0.8356532849169525
Precision for SubCategory: 0.8348256877124407
Recall for SubCategory: 0.8356532849169525
F1 Score for SubCategory: 0.8288257455616973
Confusion Matrix for SubCategory:
[[ 2  0  0 ...  0  0  0]
 [ 0  3  1 ...  0  0  0]
 [ 0  0  7 ...  0  0  0]
 ...
 [ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0 45]]

Training model for Category...
Fitting 5 folds for each of 18 candidates, totalling 90 fits


/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_split.py:737: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=5.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/feature_extraction/text.py:547: UserWarning: The parameter 'stop_words' will not be used since 'analyzer' != 'word'
  warnings.warn(


Best parameters for Category:  {'clf__alpha': 0.01, 'vect__ngram_range': (3, 5), 'vect__use_idf': True}
Accuracy for Category: 0.8597269854078408
Precision for Category: 0.8545040616810186
Recall for Category: 0.8597269854078408
F1 Score for Category: 0.8543691050203744
Confusion Matrix for Category:
[[151   1   0 ...   1   0   8]
 [  1  10   0 ...   0   0   0]
 [  0   0  25 ...   0   0   0]
 ...
 [  4   0   0 ... 149   0   0]
 [  2   0   0 ...   1   9   0]
 [  6   0   0 ...   0   0 227]]

Training model for Company...
Fitting 5 folds for each of 18 candidates, totalling 90 fits


/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_split.py:737: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=5.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/feature_extraction/text.py:547: UserWarning: The parameter 'stop_words' will not be used since 'analyzer' != 'word'
  warnings.warn(


Best parameters for Company:  {'clf__alpha': 0.1, 'vect__ngram_range': (3, 5), 'vect__use_idf': True}
Accuracy for Company: 0.8890457938269114
Precision for Company: 0.8903885242003067
Recall for Company: 0.8890457938269114
F1 Score for Company: 0.8658004306971294
Confusion Matrix for Company:
[[ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]
 [ 0  1  0 ...  0  0  0]
 ...
 [ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  1]
 [ 0  0  0 ...  0  0 27]]

Training model for Brand...
Fitting 5 folds for each of 18 candidates, totalling 90 fits


/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_split.py:737: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=5.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/feature_extraction/text.py:547: UserWarning: The parameter 'stop_words' will not be used since 'analyzer' != 'word'
  warnings.warn(


Best parameters for Brand:  {'clf__alpha': 0.01, 'vect__ngram_range': (3, 5), 'vect__use_idf': False}
Accuracy for Brand: 0.8818505816690202
Precision for Brand: 0.8997593660895931
Recall for Brand: 0.8818505816690202
F1 Score for Brand: 0.880136233834143
Confusion Matrix for Brand:
[[ 0  0  0 ...  0  0  0]
 [ 1  0  0 ...  0  0  0]
 [ 0  0  2 ...  0  0  0]
 ...
 [ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0 39]]
Predicted SubCategory for 'pepsi500': CARBONATED SOFT DRINKS
Predicted Category for 'pepsi500': BEVERAGES
Predicted Company for 'pepsi500': PEPSICO
Predicted Brand for 'pepsi500': PEPSI


In [3]:
docs_new = ['tapal danedar']  # You can add more product names as needed
processed_docs_new = [preprocess_text(doc) for doc in docs_new]

# Loop over the target columns to make predictions for each
for target in target_columns:
    predicted = models[target].predict(processed_docs_new)
    predicted_category = encoders[target].inverse_transform(predicted)
    print(f"Predicted {target} for '{docs_new[0]}': {predicted_category[0]}")

Predicted SubCategory for 'tapal danedar': TEA
Predicted Category for 'tapal danedar': BEVERAGES
Predicted Company for 'tapal danedar': TAPAL TEA
Predicted Brand for 'tapal danedar': TAPAL DANEDAR


In [5]:
from google.colab import files

# Create a zip file of the models directory
!zip -r /content/models.zip /content/models

# Download the zip file to your local machine
files.download('/content/models.zip')


  adding: content/models/ (stored 0%)
  adding: content/models/SubCategory_model.pkl (deflated 99%)
  adding: content/models/Brand_model.pkl (deflated 100%)
  adding: content/models/SubCategory_encoder.pkl (deflated 47%)
  adding: content/models/Brand_encoder.pkl (deflated 54%)
  adding: content/models/Company_model.pkl (deflated 100%)
  adding: content/models/Company_encoder.pkl (deflated 54%)
  adding: content/models/Category_encoder.pkl (deflated 35%)
  adding: content/models/Category_model.pkl (deflated 95%)


<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>